### PR TITLE
Update python-package.yml

### PR DESCRIPTION
**Pull request by jdtuck**

### CODE REVIEW

**Comment by vnmabus** [comment]
From this PR I guess that you, @jdtuck, found an identical problem as mine and your CI is failing in MacOS.

In my case, I am executing `pip install mkl-devel`, as you suggested before. Now, it tries to install an older version of `mkl-devel` (it only considers 2018.0.0 and 2018.0.3 as candidates), and it is not able to resolve them. However, on the 24th of April the CI on MacOS was just fine, and it installed `mkl-devel` in version 2023.2.1. The next CI two days later failed. I guess that version 2023.2.2 released on 25th April may have something to do with it. Do you know what is the problem?

I also wanted to ask if you considered the proposal in https://github.com/david-cortes/findblas/issues/3#issuecomment-1868931314 to use SciPy machinery to find BLAS, or any other alternative so that I don't have to install `mkl-devel` manually (maybe you can upload wheel binaries using Github actions?).

**Comment by jdtuck** [comment]
I did on the CI, but not on my local Mac. I don’t think anything is wrong with `mkl-devel` on pip, but the old version of python < 3.9 being used on the CI and compatibility. 

I did look at the proposal and I could not get it to work, if you would like to try it and see if I missed something, that would be great. I have uploaded binaries before recently, but the all the combinations it was struggling with. The problem is base python struggles when cython calls c++ that relies on BLAS. The new optimization routine uses BLAS and is much faster and I do not want to remove it from the package.

**Comment by vnmabus** [comment]
I [asked Intel](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Error-installing-mkl-devel-with-pip-on-MacOS-CI/m-p/1600644/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExXS1oxVVNZQjFIREY4fDE2MDA2NDR8U1VCU0NSSVBUSU9OU3xoSw#M36150). They refuse to support any version older than 2024.0 and they have removed MacOS support in recent versions. I still don't know if they are actively removing oldest ones or why it does suddenly not work, but we should use anything else than MKL for MacOS. Do you know if there is an alternative that just works everywhere, in order to fix my CI?

**Comment by jdtuck** [comment]
Not yet, I am working on a solution, but haven't found one yet.

**Comment by jdtuck** [comment]
I have a fix in for findblas to find openblas installed via homebrew on mac. 

david-cortes/findblas#8

After that is approved and a new release to pip, all we need to do is a `brew install openblas` for the runner and it should work. I have tested this locally on my mac.

**Comment by jdtuck** [comment]
Moving this to #53

**Comment by vnmabus** [comment]
I was able to remove the mkl-devel installation in CI, and it works again. Thank you so much!

**Pull request merged**
